#!/bin/bash
set -e

SCHEMA=$POSTGRES_DB

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -1 <<EOF
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$PUBLIC_DB_USER') THEN
      CREATE ROLE $PUBLIC_DB_USER LOGIN PASSWORD '$PUBLIC_DB_PASSWORD';
    END IF;
  END
  \$\$;

  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$INTEGRATION_DB_USER') THEN
      CREATE ROLE $INTEGRATION_DB_USER LOGIN PASSWORD '$INTEGRATION_DB_PASSWORD';
    END IF;
  END
  \$\$;

  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$ADMIN_DB_USER') THEN
      CREATE ROLE $ADMIN_DB_USER LOGIN PASSWORD '$ADMIN_DB_PASSWORD';
    END IF;
  END
  \$\$;

  CREATE SCHEMA IF NOT EXISTS $SCHEMA AUTHORIZATION $POSTGRES_USER;
  REVOKE ALL ON SCHEMA public FROM PUBLIC;

  GRANT USAGE ON SCHEMA $SCHEMA TO $PUBLIC_DB_USER;
  GRANT USAGE ON SCHEMA $SCHEMA TO $INTEGRATION_DB_USER;
  GRANT USAGE ON SCHEMA $SCHEMA TO $ADMIN_DB_USER;

  REVOKE ALL ON SCHEMA public FROM $PUBLIC_DB_USER;
  REVOKE ALL ON SCHEMA public FROM $INTEGRATION_DB_USER;
  REVOKE ALL ON SCHEMA public FROM $ADMIN_DB_USER;
  
  ALTER ROLE $PUBLIC_DB_USER SET search_path TO $SCHEMA;
  ALTER ROLE $INTEGRATION_DB_USER SET search_path TO $SCHEMA;
  ALTER ROLE $ADMIN_DB_USER SET search_path TO $SCHEMA;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT SELECT, UPDATE, INSERT ON TABLES TO $PUBLIC_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT USAGE, SELECT ON SEQUENCES TO $PUBLIC_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT REFERENCES ON TABLES TO $PUBLIC_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT SELECT, UPDATE, INSERT ON TABLES TO $ADMIN_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT USAGE, SELECT ON SEQUENCES TO $ADMIN_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT REFERENCES ON TABLES TO $ADMIN_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT ALL ON TABLES TO $INTEGRATION_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT ALL ON SEQUENCES TO $INTEGRATION_DB_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA $SCHEMA
  GRANT ALL ON FUNCTIONS TO $INTEGRATION_DB_USER;

  GRANT ALL ON SCHEMA $SCHEMA TO $INTEGRATION_DB_USER;

  CREATE EXTENSION IF NOT EXISTS citext;
EOF